[package]
name = "littleduck"
version = "0.1.0"
edition = "2021"

[[bin]]
doc = false
name = "littleduck"

[build-dependencies]
cfgrammar = "0.11"
lrlex = "0.11"
lrpar = "0.11"

[dependencies]
cfgrammar = "0.11"
lrlex = "0.11"
lrpar = "0.11"
